### ISSUE TITLE
Showcase: QButtonUI Demo Exception

### ISSUE THREAD

**Issue by mickleness** [mickleness/pumpernickel#56]
When you scale the QButtonUI demo too small you get an exception:

```
java.lang.IllegalArgumentException: Width (53) and height (0) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at com.pump.plaf.SimpleButtonFill.getFill(SimpleButtonFill.java:89)
	at com.pump.plaf.QButtonUI.paintBackground(QButtonUI.java:1358)
	at com.pump.plaf.QButtonUI.paint(QButtonUI.java:1322)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at com.pump.plaf.QComboBoxUI.paintCurrentValueBackground(QComboBoxUI.java:524)
	at javax.swing.plaf.basic.BasicComboBoxUI.paint(BasicComboBoxUI.java:903)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
```

**Comment by mickleness** [comment]
Closing as resolved in v1.02: now in SimpleButtonFill we make sure the width & height are at least 1.

... but also: this should be CNR, because the previous QButtonUI demo is removed and in the new demo you don't have the option to scale the buttons.
